version: '3.2'

services:
  scr-torb:
    image: dperson/torproxy
    container_name: scr-torb
    ports:
      - '8119:8119'
      - '9052:9052'
    networks:
      - webappnetwork
  web:
    container_name: scraper-serverTM
    build: .
    depends_on:
      - scr-torb
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
